### PR TITLE
feat: useController

### PR DESCRIPTION
**Pull request by bennypowers**
Given
```ts
class SimpleController implements ReactiveController {
  host: ReactiveControllerHost;

  #x = '';

  get x() { return this.#x; }
  set x(v) {
    this.#x = v;
    this.host.requestUpdate();
  }

  constructor(host, value) {
    this.host = host;
    this.x = value;
    host.addController(this);
  }
}
```

Then

```js
it("use-controller", async () => {
  const hooks = createHooks(() => {});

  let controller;

  const useSimple = x =>
    useController(host =>
      new SimpleController(host, x));

  hooks.load(() => {
    controller = useSimple('x');
  });

  await controller.host.updateComplete;
  expect(controller.x, 'initial value').to.equal('x');

  controller.x = 'y';

  await controller.host.updateComplete;
  expect(controller.x, 'updated value').to.equal('y');

  controller.x = 'z';

  await controller.host.updateComplete;
  expect(controller.x, 'user value').to.equal('z');
});
```

### CODE REVIEW

**Comment by UpperCod** [comment]
Hi, I have made a change, which allows to keep the types when exporting the module,  I await your review if you agree with this

**Comment by bennypowers** [comment]
Your changes are good, thanks.

I adjusted the host API to match `@lit-labs/react`

And I added a hack in the test file to prevent it from stalling. testing with `createHooks` will timeout unless the test manually resolved the updateComplete promise, whereas this test passes:

```js
import { useHost, useEffect, c } from 'atomico';
import { fixture } from 'atomico/test-dom';

it("use-controller", async () => {
  const useSimple = x =>
    useController(host =>
      new SimpleController(host, x));

  function Renderer() {
    const ref = useHost();
    const controller = useSimple('x');
    useEffect(() => {
      ref.current.controller = controller;
    }, [controller]);
    return html`<host>${controller.x}</host>`;
  }

  const Component = 'use-controller-element';
  customElements.define(Component, c(Renderer));

  const element = fixture(html`<${Component}></${Component}>`);

  await element.updated;
  expect(element.controller.x, 'initial value').to.equal('x');

  element.controller.x = 'y';

  await element.updated;
  expect(element.controller.x, 'updated value').to.equal('y');

  element.controller.x = 'z';

  await element.updated;
  expect(element.controller.x, 'user value').to.equal('z');
});
```

**Comment by bennypowers** [comment]
That's great, thank you for merging.

FYI I get some [console errors in my tests](https://github.com/apollo-elements/apollo-elements/runs/3060485428?check_suite_focus=true#step:7:19), although they do eventually pass

e.g.

```
 TypeError: Cannot read property '$$' of undefined
  at render (node_modules/atomico/src/render.js:99:70)
  at node_modules/atomico/src/element/custom-element.js:68:33
```

I've included atomico support in [`@apollo-elements/atomico@next`](https://npm.im/@apollo-elements/atomico) and you can check out the [docs and demos on the site](https://next.apolloelements.dev/api/libraries/atomico/)

**Comment by UpperCod** [comment]
Thanks for the log, I will review the commented.

**Pull request merged**
